import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/Main.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>SKKU Medical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.banner}>
          <h3>SKKU Medical</h3>
          <p>
            SKKU Medical은 병원 진료 정보 공유 서비스를 통해 사람들이 타지역
            병원을 심리적 거리낌 없이 이용할 수 있도록 돕기 위해 제작된
            서비스입니다.
          </p>
        </div>
        <div className={styles.navigator}>
          <Link href={"/"} className={styles.qr}>
            <div className={styles.qrImage}>
              <Image
                layout="responsive"
                src={"/qr-img.png"}
                alt="Dog pic"
                width={100}
                height={100}
              />
            </div>
            <span>{"< "}QR 코드 확인</span>
          </Link>
          <Link href={"/"} className={styles.diagnose}>
            <div className={styles.diagnoseImage}>
              <Image
                layout="responsive"
                src={"/prescript-img.webp"}
                alt="prescript image"
                width={100}
                height={100}
              />
            </div>
            <span href="/diagnose">진단 결과 확인{" >"}</span>
          </Link>
        </div>
      </main>
    </>
  );
}
