name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: test and deploy flask app to S3 bucket
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Check current directory and contents
      run: |
        pwd
        ls -la
    
    - name: run unittest
      run: |
        cd test
        python -m unittest test/test.py
    
    - name: make artifacts dir
      run: mkdir artifacts

    - name: zip artifacts
      run: |
        zip -r artifacts/build.zip app/ appspec.yml

    - name: deploy to s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: skkuthon1
        AWS_ACCESS_KEY_ID: AKIAWUAT2OPE4IMKYDEM
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: ap-northeast-2
        SOURCE_DIR: 'artifacts'
        DEST_DIR: 'backend'


